accidentdetection/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from .views import home, about, contact

app_name = "accidentdetection"

urlpatterns = [
    path('', include('detector.urls')),
    path('home', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('detector/', include('detector.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accidentdetectionapi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classifier/', include("classifier.urls"))
]

accounts/urls.py
from django.urls import path
from .views import login_user, logout_user, register_user

app_name = 'accounts'

urlpatterns = [
    path('login', login_user, name='login'),
    path('logout', logout_user, name='logout'),
    path('register', register_user, name='register'),
    # other URL patterns...
]

detector/urls.py
from django.urls import path
from .views import dashbord, process_video,  view_single, view_images,  export_csv

app_name = 'detector'
urlpatterns = [
    path('', dashbord),
    path('process_video', process_video, name='process_video'),
    path('view_images', view_images, name='view_images'),
    path('dashbord', dashbord, name='dashbord'),
    path('export_csv', export_csv,  name='export_csv'),
    path('view_single/<str:id>', view_single, name='view_single'),
]

accidentdetection/views.py
from django.shortcuts import render

#  Create your views here.

def home(request):
    return render(request,'accidentdetection/home.html')

def about(request):
    return render(request,'accidentdetection/about.html')

def contact(request):
    return render(request,'accidentdetection/contact.html')

accidentdetection/templates/accidentdetection/about.html
{% extends 'accidentdetection/base.html'%} {% load static %} {% block title %}
About {% endblock title%} {% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6">
      <h1 class="fw-bold">About Accident Detection System</h1>
      <p>
        Accident Detection System is an application that uses computer vision
        and machine learning techniques to detect and classify road accidents in
        real time. The system can process live video feeds from cameras
        installed in different locations on the road network, and can detect
        various types of accidents, including collisions, rollovers, and other
        types of incidents.
      </p>
      <p>
        The system uses deep learning algorithms to analyze video frames in real
        time, and can automatically generate alerts and notifications to
        emergency services, such as police, ambulance, and fire departments. The
        system can also provide real-time updates to traffic management centers
        and other stakeholders, helping them to quickly respond to accidents and
        minimize the impact on traffic flow and safety.
      </p>
    </div>
    <div class="col-md-6">
      <img
        src="https://via.placeholder.com/500x400"
        class="img-fluid rounded"
        alt="Accident Detection System"
      />
    </div>
  </div>
</div>
{% endblock content%}

accidentdetection/templates/accidentdetection/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,600;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Anek+Telugu&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="{% static 'css/bootstrap/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'css/bootstrap/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'css/aos/aos.css" rel="stylesheet' %}" />

    <title>AccidentDetectionAi</title>
    <style>
      .login input {
        padding: 0.75em;
        border: 1px solid gray;
        border-radius: 0.5em;
      }

      .login label {
        font-size: medium;
      }

      h1,
      h2,
      h3,
      h4,
      h5 {
        font-family: "Anek Telugu", Arial, Helvetica, sans-serif;
      }

      .sidebar {
        background-color: #f5f5f5;
        border: 1px solid #c2c2c2;
        /* height: 100vh; */
      }

      .nav-link {
        color: #333;
      }

      .active {
        font-weight: bold;
      }

      .nav-link:hover {
        color: #007bff;
      }
    </style>
  </head>
  <body
    class=""
    style="
      font-family: Poppins, system-ui, -apple-system, BlinkMacSystemFont,
        'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans',
        'Helvetica Neue', sans-serif;
    "
  >
    <header>
      <nav
        class="p-3 navbar navbar-expand-lg rounded"
        aria-label="Thirteenth navbar example"
        style="background: #fff"
      >
        <div class="container-fluid">
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarsExample11"
            aria-controls="navbarsExample11"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div
            class="px-5 collapse navbar-collapse d-lg-flex"
            id="navbarsExample11"
          >
            <a class="navbar-brand col-lg-3 me-0" href="/home"
              ><h2 class="fw-bold">
                AccidentDetection<span class="text-primary">Ai</span>
              </h2></a
            >
            <ul class="navbar-nav col-lg-6 justify-content-lg-center">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="/home">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'detector:process_video'%}"
                  >Watch</a
                >
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="/about">About</a>
              </li>
            </ul>
            {% if user.is_authenticated %}
            <form action="{% url 'accounts:logout' %}" method="POST" class="">
              {%csrf_token%}
              <a href="/about" class="btn border-success text-success"
                >Contact us</a
              >
              <button
                type="submit"
                class="btn btn-danger text-weight-bold"
                value="Let me out"
              >
                Logout
              </button>
              {% else %}
              <a href="{% url 'accounts:login'%}" class="btn btn-primary"
                >Login</a
              >
              <a
                href="{% url 'accounts:register'%}"
                class="btn mx-md-2 btn-warning"
                >Start For Free</a
              >
              {% endif %}
            </form>
          </div>
        </div>
      </nav>
    </header>
    <div class="mt-5">{% block content %}{% endblock content %}</div>
    <script src=""></script>
    <div class="bg-light">
      <footer class="p-5">
        <div class="row">
          <div class="col-6 col-md-2 mb-3">
            <h5>Company</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2">
                <a href="/about" class="nav-link p-0 text-muted">About Us</a>
              </li>
              <li class="nav-item mb-2">
                <a href="#" class="nav-link p-0 text-muted">Careers</a>
              </li>
              <li class="nav-item mb-2">
                <a href="#" class="nav-link p-0 text-muted">FAQs</a>
              </li>
            </ul>
          </div>

          <div class="col-6 col-md-2 mb-3">
            <h5>Resources</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2">
                <a href="#" class="nav-link p-0 text-muted">Video</a>
              </li>
              <li class="nav-item mb-2">
                <a href="#" class="nav-link p-0 text-muted">Blogs</a>
              </li>
              <!-- <li class="nav-item mb-2">
                <a href="#" class="nav-link p-0 text-muted">Community</a>
              </li>
              <li class="nav-item mb-2">
                <a href="/support" class="nav-link p-0 text-muted">Support</a>
              </li> -->
            </ul>
          </div>

          <div class="col-6 col-md-2 mb-3">
            <h5>Product</h5>
            <ul class="nav flex-column">
              <li class="nav-item mb-2">
                <a href="#" class="nav-link p-0 text-muted"
                  >AccidentDetectonAi</a
                >
              </li>
              <li class="nav-item mb-2">
                <a href="#" class="nav-link p-0 text-muted">Benefits</a>
              </li>
              <li class="nav-item mb-2">
                <a href="#" class="nav-link p-0 text-muted">Why Ai</a>
              </li>
            </ul>
          </div>

          <div class="col-md-5 offset-md-1 mb-3">
            <form>
              <h5>Subscribe to our newsletter</h5>
              <p>Monthly digest of what's new and exciting from us.</p>
              <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                <label for="newsletter1" class="visually-hidden"
                  >Email address</label
                >
                <input
                  id="newsletter1"
                  type="text"
                  class="form-control"
                  placeholder="Email address"
                />
                <button class="btn btn-primary" type="button">Subscribe</button>
              </div>
            </form>
          </div>
        </div>

        <div
          class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top"
        >
          <p>&copy; 2023 AccidentDetectionAi. All rights reserved.</p>
          <ul class="list-unstyled d-flex">
            <li class="ms-3">
              <a class="link-dark" href="#"
                ><svg class="bi" width="24" height="24">
                  <use xlink:href="#twitter" /></svg
              ></a>
            </li>
            <li class="ms-3">
              <a class="link-dark" href="#"
                ><svg class="bi" width="24" height="24">
                  <use xlink:href="#instagram"></use>
                </svg>
              </a>
            </li>
            <li class="ms-3">
              <a class="link-dark" href="#"
                ><svg class="bi" width="24" height="24">
                  <use xlink:href="#facebook" /></svg
              ></a>
            </li>
          </ul>
        </div>
      </footer>
    </div>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

accidentdetection/templates/accidentdetection/contact.html
{% extends 'accidentdetection/base.html'%}
{% load static %}
{% block title %} 
Contact
{% endblock title%}
{% block content %}
<h1>Contact</h1>
{% endblock content%}

accidentdetection/templates/accidentdetection/home.html
{% extends 'accidentdetection/base.html'%}
{% load static %}
{% block title %} 
Home
{% endblock title%}
{% block content %}
<h1>Home</h1>
{% endblock content%}