accidentdetection/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings
from .views import home, about, contact

app_name = "accidentdetection"

urlpatterns = [
    path('', include('detector.urls')),
    path('home', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('detector/', include('detector.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accidentdetectionapi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classifier/', include("classifier.urls"))
]

accounts/urls.py
from django.urls import path
from .views import login_user, logout_user, register_user

app_name = 'accounts'

urlpatterns = [
    path('login', login_user, name='login'),
    path('logout', logout_user, name='logout'),
    path('register', register_user, name='register'),
    # other URL patterns...
]

detector/urls.py
from django.urls import path
from .views import dashbord, process_video,  view_single, view_images,  export_csv

app_name = 'detector'
urlpatterns = [
    path('', dashbord),
    path('process_video', process_video, name='process_video'),
    path('view_images', view_images, name='view_images'),
    path('dashbord', dashbord, name='dashbord'),
    path('export_csv', export_csv,  name='export_csv'),
    path('view_single/<str:id>', view_single, name='view_single'),
]

detector/models.py
from django.db import models

class Prediction(models.Model):
    image = models.CharField(max_length=255)
    prediction = models.IntegerField()
    confidence = models.FloatField()
    date = models.CharField(max_length=255, default="not_set")
    time = models.CharField(max_length=255, default='not_set')
    location = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.prediction} with {self.confidence}% confidence at {self.date,  self.time} in {self.location}"

detector/views.py
import os, cv2, csv, pathlib
from datetime import datetime
from .models import Prediction
from django.http import HttpResponse
from shafaratoolkit.props import colored
import accidentdetection.settings as settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .tools import request_prediction, get_user_location, send_message


# Create your views here.
BASE_DIR = pathlib.Path(__file__).resolve().parent.parent

model_api = "http://127.0.0.1:8081/classifier/"
messaging_api = 'https://geniussmsgroup.com/api/json/messages1/jsonMessagesService'


def save_prediction(response, location, date_time, frame_count):
    prediction_object = Prediction(
        prediction=response['prediction'],
        confidence=str(round(response['confidence'], 2)),
        location=location,
        time=date_time.time().strftime("%H:%M:%S"),
        date=date_time.date().strftime("%Y-%m-%d"),
        image=f'frame_{frame_count}.jpg'
    )

    prediction_object.save()

    return prediction_object

# @login_required(login_url='/accounts/login')


def process_video(request):
    if request.method == 'POST':
        video_url = request.POST.get('video_url')
        print(colored(0, 0, 256, f'{video_url  }'))
        video_path = os.path.join(settings.STATIC_ROOT, 'videos', video_url)
        output_dir = os.path.join(settings.MEDIA_ROOT, 'images', 'frames')
        prediction_dir = os.path.join(
            settings.MEDIA_ROOT, 'images', 'predictions')

        if not os.path.exists(output_dir):
            os.makedirs(output_dir)

        if not os.path.exists(prediction_dir):
            os.makedirs(prediction_dir)

        try:
            location = get_user_location(request)
        except Exception as e:
            print(colored(0, 0, 255, f'Failed getting user location {str(e)}'))
            print(colored(0, 0, 255, f'Setting to default location'))
            location = 'Makerere,Kikoni, Kampala (U)'

        date_time = datetime.now()

        video = cv2.VideoCapture(video_path)

        frame_count = 0
        frame_frequency = 1000
        while True:
            success, frame = video.read()

            if not success:
                break

            if frame_count % frame_frequency == 0:
                output_path = os.path.join(
                    output_dir, f'frame_{frame_count}.jpg')
                cv2.imwrite(output_path, frame)

                response = request_prediction(output_path, model_api)

                if response == None:
                    context = {
                        'error_message': 'Can not get response from the model at this time',
                        'status': 500
                    }

                    return render(request, 'detector/error_page.html', context=context)

                if response['prediction'] == 1:
                    send_message(
                        messaging_api=messaging_api,
                        numbers=['256709603955', '256701520768', '256708563752'],
                        confidence=response['confidence'],
                        location=location,
                        date_time=date_time
                    )

                save_prediction(response, location, date_time, frame_count)

            frame_count += 1

        video.release()

        return redirect('/detector/dashbord')

    if request.method == 'GET':
        context = {}
        return render(request, 'detector/select_video.html', context=context)

# @login_required(login_url='/accounts/login')


def dashbord(request):
    latest_predictions = Prediction.objects.all()
    num_images_processed = len(latest_predictions)
    num_accidents_detected = len(
        [p for p in latest_predictions if p.prediction == 1])

    try:
        prediction_confidence = round(
            sum([float(p.confidence) for p in latest_predictions])/len(latest_predictions), 2)
    except Exception as e:
        prediction_confidence = 0

    context = {
        'latest_predictions': latest_predictions,
        'num_images_processed': num_images_processed,
        'num_accidents_detected': num_accidents_detected,
        'prediction_confidence': prediction_confidence,
    }
    return render(request, 'detector/dashbord.html', context)

# @login_required(login_url='/accounts/login')


def view_single(request, id):
    prediction = Prediction.objects.get(id=id)

    context = {
        'prediction': prediction,
    }
    return render(request, 'detector/view_single.html', context=context)


def view_images(request):
    latest_predictions = Prediction.objects.all()
    context = {
        'latest_predictions': latest_predictions,
    }
    return render(request, 'detector/view_images.html', context=context)


def export_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="predictions.csv"'

    writer = csv.writer(response)
    writer.writerow(['ID', 'Prediction', 'Confidence',
                    'Location', 'Time', 'Date', 'Image'])

    for prediction in Prediction.objects.all().values_list(
            'id', 'prediction', 'confidence', 'location', 'time', 'date', 'image'):
        writer.writerow(prediction)

    return response

detector/templates/detector/dashbord.html
{% extends 'accidentdetection/base.html'%} {% load static %} {% block content %}
<style>
  .images-card {
    background: rgb(206, 252, 206);
  }

  .accidents-card {
    background: rgb(250, 204, 204);
  }

  .confidence-card {
    background: rgb(210, 243, 254);
  }
</style>
<div class="container-fluid">
  <div class="row p-3">
    <div class="col-md-3 bg-light sidebar rounded p-3">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'detector:dashbord'%}">
            <i class="bi bi-speedometer2 me-3"></i> Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'detector:process_video'%}">
            <i class="bi bi-camera-video me-3"></i> Select Video Feed
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'detector:view_images'%}">
            <i class="bi bi-image me-3"></i> View Images
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'detector:export_csv'%}">
            <i class="bi bi-download me-3"></i> Export Data
          </a>
        </li>
      </ul>
    </div>
    <div class="col-md-9 main p-3">
      <h2 class="fw-bold">Dashboard</h2>
      <div class="row">
        <div class="col-md-4">
          <div class="card m-1 shadow images-card">
            <div class="card-body">
              <h4 class="card-title">Images Processed</h4>
              <p class="card-text">{{ num_images_processed }}</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card m-1 shadow accidents-card">
            <div class="card-body">
              <h4 class="card-title">Accidents Detected</h4>
              <p class="card-text">{{ num_accidents_detected }}</p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card m-1 shadow confidence-card">
            <div class="card-body">
              <h4 class="card-title">Prediction Confidence</h4>
              <p class="card-text">{{ prediction_confidence }}%</p>
            </div>
          </div>
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Latest Predictions</h4>
              <div class="table-responsive">
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Time</th>
                      <th>Location</th>
                      <th>Prediction</th>
                      <th>Confidence</th>
                      <th>Image</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for prediction in latest_predictions %}
                    <tr>
                      <td>{{ prediction.date }}</td>
                      <td>{{ prediction.time }}</td>
                      <td>{{ prediction.location }}</td>
                      <td>{{ prediction.prediction }}</td>
                      <td>{{ prediction.confidence }}</td>
                      <td>
                        <a
                          href="{% url 'detector:view_single' id=prediction.id %}"
                          >{{ prediction.image }}</a
                        >
                      </td>
                    </tr>
                    {% empty %}
                    <tr>
                      <td colspan="6">No predictions found.</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

detector/templates/detector/error_page.html
{% extends 'accidentdetection/base.html'%} {% load static %} {% block content%}

<style>
    .error{
        background: rgb(247, 203, 203);
        color: rgb(191, 39, 39);
        border: 1px solid rgb(191, 39, 39);
    }
    
</style>
<div class="container-fluid">
  <div class="row p-3">
    <div class="col-md-3 bg-light sidebar rounded p-3">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'detector:dashbord'%}">
            <i class="bi bi-speedometer2 me-3"></i> Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'detector:process_video'%}">
            <i class="bi bi-camera-video me-3"></i> Select Video Feed
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'detector:view_images'%}">
            <i class="bi bi-image me-3"></i> View Images
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'detector:export_csv'%}">
            <i class="bi bi-download me-3"></i> Export Data
          </a>
        </li>
      </ul>
    </div>
    <div class="col-md-9 main p-3">
      <h1 class="fw-bold text-center">An Error Occurred</h1>
      <div class="m-auto rounded p-5 error">
          <p><span class="fw-bold">Code: </span>{{status}}</p>
        <p><span class="fw-bold">Message: </span>{{error_message}}</p>
      </div>
    </div>
  </div>
</div>

{% endblock %}

detector/templates/detector/select_video.html
{% extends 'accidentdetection/base.html'%} {% load static %} {% block content%}
<div class="container-fluid">
  <div class="row p-3">
    <div class="col-md-3 bg-light sidebar rounded p-3">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'detector:dashbord'%}">
            <i class="bi bi-speedometer2 me-3"></i> Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'detector:process_video'%}">
            <i class="bi bi-camera-video me-3"></i> Select Video Feed
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'detector:view_images'%}">
            <i class="bi bi-image me-3"></i> View Images
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'detector:export_csv'%}">
            <i class="bi bi-download me-3"></i> Export Data
          </a>
        </li>
      </ul>
    </div>
    <div class="col-md-9 main p-3">
      <h1 class="fw-bold text-center">Select Video Feed</h1>
      <!-- HTML form using Bootstrap -->
      <form
        method="post"
        enctype="multipart/form-data"
        action="{% url 'detector:process_video' %}"
        class="flex flex-column justify-content-center m-auto"
        style="width: 60%"
      >
        {% csrf_token %}
        <div class="form-group">
          <label for="video_url">Select a video URL to process:</label>
          <select class="form-control mb-3" id="video_url" name="video_url">
            <option value="">-- Select a video URL --</option>
            <option value="compilation.mp4">
              https://example.com/video1.mp4
            </option>
            <option value="video2.mp4">https://example.com/video2.mp4</option>
            <option value="video3.mp4">https://example.com/video3.mp4</option>
          </select>
        </div>
        <button type="submit" class="btn btn-primary text-center mb-3">
          Process Video
        </button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

detector/templates/detector/view_images.html
{% extends 'accidentdetection/base.html'%}
{% load static %}
{% block content%}
<div class="container-fluid">
    <div class="row p-3">
    <div class="col-md-3 bg-light sidebar rounded p-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'detector:dashbord'%}">
              <i class="bi bi-speedometer2 me-3"></i> Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'detector:process_video'%}">
              <i class="bi bi-camera-video me-3"></i> Select Video Feed
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'detector:view_images'%}">
              <i class="bi bi-image me-3"></i> View Images
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'detector:export_csv'%}">
              <i class="bi bi-download me-3"></i> Export Data
            </a>
          </li>
        </ul>
      </div>
    <div class="col-md-9 main">
        <div class="flex">
            {% for prediction in latest_predictions %}
            <a 
                href="{% url 'detector:view_single' id=prediction.id %}"
            >
                <img 
                    src="/media/images/frames/{{prediction.image}}" 
                    alt="{{prediction.image}}"
                    width="150px"
                    style="border-radius: 5px;"
                    class="rounded p-2 img-fluid" 
                >
            </a>
            {% empty %}
            <p>No images found</p>
            {% endfor %}
        </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

detector/templates/detector/view_single.html
{% extends 'accidentdetection/base.html'%}
{% load static %}
{% block content%}
<div class="container-fluid">
    <div class="row p-3">
    <div class="col-md-3 bg-light sidebar rounded p-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'detector:dashbord'%}">
              <i class="bi bi-speedometer2 me-3"></i> Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'detector:process_video'%}">
              <i class="bi bi-camera-video me-3"></i> Select Video Feed
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'detector:view_images'%}">
              <i class="bi bi-image me-3"></i> View Images
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'detector:export_csv'%}">
              <i class="bi bi-download me-3"></i> Export Data
            </a>
          </li>
        </ul>
      </div>
    <div class="col-md-9 main">
        <div class="">
            <div class="d-flex details p-3">
              <p class="">Prediction: {{prediction.prediction}}</p>
              <p class="px-2">Confidence: {{prediction.confidence}}%</p>
              <p class="px-2">Location: {{prediction.location}}</p>
              <p class="">Time: {{prediction.time}}</p>
            </div>
            <img 
                src="/media/images/frames/{{ prediction.image }}" 
                alt="{{ prediction.image }}" 
                srcset=""
                class="rounded"
                width=""
            >
        </div>
    </div>
  </div>
</div>
</div>

{% endblock %}